### PR TITLE
Enhance role-assignment plugin

### PR DESCRIPTION
**Pull request by officialpiyush**
# What's Changed?

* Renamed `self.message_ids` to `self.ids` as it stores channel id's too now.
* Made `self.ids` a dictionary, so now, we have it in `{message_id: channel_id}` format.
* Added loop to update the db with id's .
* If the thread is deleted, its removed from db.

# Want Changes?

* Sure! Just Comment What changes you need

### CODE REVIEW

**Comment by officialpiyush** [comment]
# Additions In Latest Commit - https://github.com/papiersnipper/modmail-plugins/pull/5/commits/00bb3ef5283ace5d07d808f5e9c1447f962ebbdd

* Added a log command `role log #channel`, by which people can check who added the role to the user or removed it

**Comment by officialpiyush** [comment]
# How Do Logs Look?

image

**Comment by officialpiyush** [comment]
# Status

* Everything Works as intended and no errors occured while testing with my instance, so this can be merged

**Comment by papiersnipper** [comment]
Hi, thanks for the work! I don't really like the idea of a log channel, so please remove that. Also, those comments, I'm not a big fan of them so please remove them

**Comment by officialpiyush** [comment]
Sure, I kept those comments for you to understand

**Comment by officialpiyush** [comment]
Done, logs are gone now

**Comment by officialpiyush** [comment]
Please don't merge until I commit a fix to saisko's issue

**Comment by officialpiyush** [comment]
Everything Fixed, can be merged

**Pull request merged**
